@CarvedRock.Aot.Api_HostAddress = http://localhost:5000

POST https://demo.duendesoftware.com/connect/token
Content-Type: application/x-www-form-urlencoded

client_id=m2m&client_secret=secret&grant_type=client_credentials&scope=api

###

@access_token = eyJhbGciOiJSUzI1NiIsImtpZCI6IkMyNTJGOUNBQjc3Q0MxNTQwNTBFMTg1NTk5MjJCMTJGIiwidHlwIjoiYXQrand0In0.eyJpc3MiOiJodHRwczovL2RlbW8uZHVlbmRlc29mdHdhcmUuY29tIiwibmJmIjoxNzA0MjgxOTUzLCJpYXQiOjE3MDQyODE5NTMsImV4cCI6MTcwNDI4NTU1MywiYXVkIjoiYXBpIiwic2NvcGUiOlsiYXBpIl0sImNsaWVudF9pZCI6Im0ybSIsImp0aSI6IjUzNTY4M0EwOENBRTU4RThEQjVEMjYwQkNDRTAwREZCIn0.GnH_rnFb-hOnjD2_2fEmPvMwG2G3ydX2hAnNVMImldc9fCHpi-iSKI8VS-KJKtZTWtZnxTilfrS76ut5M8Kc_-mFE2OAMJ4xcEtQiiZTKzYna84RWhXct39mn9BDgqDEQJImz1UDDOAd1M1yslQONgsH4DboDa1aqmYayQFosZBRsG9CjyPd9tiNKTycWcPojWCUCHo1yUkA-vJBFouo0K1701jQCG8VD9RcBJI4J3-8h5GLtM0MojIkmLGBWogivvGtsEzjtvkHViTCLhKJIaYWCHTzZ_stRA6OPyd8NO8Eo6m7GsM0BfOTkou8MMkegYyXtQjdYr_n7qkb2eZo3A

GET {{CarvedRock.Aot.Api_HostAddress}}/products
Authorization: Bearer {{access_token}}
Accept: application/json

###

GET {{CarvedRock.Aot.Api_HostAddress}}/products?category=equip
Authorization: Bearer {{access_token}}
Accept: application/json

###

## this request will fail with 500 error (throws exception)
GET {{CarvedRock.Aot.Api_HostAddress}}/products?category=error
Authorization: Bearer {{access_token}}
Accept: application/json

###
GET {{CarvedRock.Aot.Api_HostAddress}}/todos/
Accept: application/json

###

GET {{CarvedRock.Aot.Api_HostAddress}}/todos/1
Accept: application/json

###
